In [2]:
import pandas as pd

In [35]:
med = pd.read_csv('C:/Users/user/LikeLion_AI/data/CSV/Medical_Check_1_50000.csv')
med_100 = pd.read_csv('C:/Users/user/LikeLion_AI/data/CSV/Medical_Check_1_1000000.csv')
med_100

,기준년도,가입자 일련번호,시도코드,성별코드,연령대 코드(5세단위),신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,결손치 유무,치아마모증유무,제3대구치(사랑니) 이상,치석,데이터 공개일자
0,2019,1,11,1,13,165,65,90.0,1.5,1.2,...,47.0,2.0,NaN,1,0.0,미시행,미시행,미시행,1.0,20191231
1,2019,2,48,2,5,155,45,64.0,1.2,0.5,...,13.0,1.0,1.0,0,NaN,미시행,미시행,미시행,NaN,20191231
2,2019,3,41,1,13,160,70,87.0,0.9,0.8,...,17.0,1.0,1.0,0,NaN,미시행,미시행,미시행,NaN,20191231
3,2019,4,28,1,12,170,60,85.0,0.4,1.2,...,32.0,2.0,1.0,0,NaN,미시행,미시행,미시행,NaN,20191231
4,2019,5,41,1,10,170,70,81.2,0.7,0.7,...,19.0,2.0,NaN,0,NaN,미시행,미시행,미시행,NaN,20191231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2019,999996,41,1,12,170,65,80.0,1.0,1.2,...,21.0,1.0,1.0,0,NaN,미시행,미시행,미시행,NaN,20191231
999996,2019,999997,11,1,9,170,55,75.0,0.9,0.8,...,27.0,2.0,1.0,0,NaN,미시행,미시행,미시행,NaN,20191231
999997,2019,999998,45,1,13,160,65,92.3,1.0,0.9,...,84.0,2.0,1.0,1,0.0,미시행,미시행,미시행,0.0,20191231
999998,2019,999999,30,1,8,170,75,85.0,0.8,0.8,...,29.0,2.0,1.0,1,0.0,미시행,미시행,미시행,0.0,20191231
999999,2019,1000000,11,2,10,155,65,86.0,0.5,0.5,...,9.0,1.0,NaN,1,0.0,미시행,미시행,미시행,1.0,20191231

In [22]:
med1 = med.drop(['결손치 유무', '치아마모증유무', '제3대구치(사랑니) 이상'], axis=1)
med1.columns

Index(['기준년도', '가입자 일련번호', '시도코드', '성별코드', '연령대 코드(5세단위)', '신장(5Cm단위)',
       '체중(5Kg 단위)', '허리둘레', '시력(좌)', '시력(우)', '청력(좌)', '청력(우)', '수축기 혈압',
       '이완기 혈압', '식전혈당(공복혈당)', '총 콜레스테롤', '트리글리세라이드', 'HDL 콜레스테롤', 'LDL 콜레스테롤',
       '혈색소', '요단백', '혈청크레아티닌', '(혈청지오티)AST', '(혈청지오티)ALT', '감마 지티피', '흡연상태',
       '음주여부', '구강검진 수검여부', '치아우식증유무', '치석', '데이터 공개일자'],
      dtype='object')

11 서울특별시 41 경기도 42 강원도

26 부산광역시 27 대구광역시 28 인천광역시 29 광주광역시 30 대전광역시 31 울산광역시 36 세종특별자치시

43 충청북도 44 충청남도 45 전라북도 46 전라남도 47 경상북도 48 경상남도 49 제주특별자치도

In [19]:
med1['시도코드'].value_counts()

41    12664
11     8889
48     3437
26     3311
28     3010
47     2658
27     2309
44     2093
46     1826
43     1774
45     1738
30     1461
42     1422
29     1365
31     1204
50      577
36      262
Name: 시도코드, dtype: int64

In [23]:
med1['시도코드'] = med1['시도코드'].map({11: '서울특별시', 41: '경기도', 42: '강원도', 26: '부산광역시', 27: '대구광역시', 28: '인천광역시',
                                 29: '광주광역시', 30: '대전광역시', 31: '울산광역시', 36: '세종특별자치시', 
                                 43: '충청북도', 44: '충청남도', 45: '전라북도', 46: '전라남도', 47: '경상북도', 48: '경상남도', 49: '제주특별자치도'})

med1['시도코드']

0        서울특별시
1         경상남도
2          경기도
3        인천광역시
4          경기도
         ...
49995      경기도
49996      경기도
49997    대구광역시
49998    서울특별시
49999      경기도
Name: 시도코드, Length: 50000, dtype: object

In [24]:
med1.groupby('시도코드')['신장(5Cm단위)'].mean()

시도코드
강원도        161.395921
경기도        162.731364
경상남도       162.279604
경상북도       162.086155
광주광역시      162.717949
대구광역시      162.293201
대전광역시      162.518823
부산광역시      162.295379
서울특별시      162.236472
세종특별자치시    163.874046
울산광역시      163.920266
인천광역시      162.081395
전라남도       161.073384
전라북도       160.949367
충청남도       162.692308
충청북도       161.854566
Name: 신장(5Cm단위), dtype: float64

In [42]:
med_101 = med_100.drop(['결손치 유무', '치아마모증유무', '제3대구치(사랑니) 이상'], axis=1)
print(med_101['시도코드'].value_counts().sort_index())   # 값을 세면서 오름차순 배열
# med_101.sort_values(by='시도코드')

11    179491
26     66484
27     46409
28     58555
29     27327
30     29423
31     24162
36      5474
41    255131
42     29769
43     33588
44     43047
45     35218
46     36138
47     52472
48     66202
50     11110
Name: 시도코드, dtype: int64